apiVersion: "v1"
kind: "DeploymentConfig"
metadata:
  name: "nifiregistry"
spec:
  replicas: 1
  selector:
    app: "nifiregistry"
  template:
    metadata:
      labels:
        app: "nifiregistry"
    spec:
      containers:
      - name: "nifiregistry-container"
        image: "apache/nifi-registry:latest"
        ports:
        - containerPort: 18080
          name: http
        - containerPort: 22
          name: ssh
        resources:
          requests:
            cpu: ".5"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "1Gi"
        env:
        - name: VERSION
          value: "11"